[project]
name = "task-manager-mcp"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "mcp[cli]>=1.5.0",
    "pytest>=7.0.0"
]

[project.optional-dependencies]
test = [
    "pytest-cov>=3.0.0"
]
